#' @title Run inhaler analysis with new data
#' @description Runs the inhaler example from brms/brm with new data set.
#' It is assumed that a a structure brmsfit has been generated by 
#' \code{brms/generate_stan.R}.
#' @param newdata New data set of the same structure as \code{inhaler} 
#' in `brms`
#' @return A structure of class brmsfit
#'
#' @useDynLib brmspack
#' @importFrom graphics plot
#' @importFrom stats update
#' @importFrom utils data
#' @importFrom stats getCall
#' @importFrom Rcpp loadModule
#'
#' @examples
#' run_inhaler()
#' @export
run_inhaler = function(newdata){
  mod = stanmodels[["inhaler"]] # Not yet used
  # load inhaler_model 
  model_file = system.file("extdata/inhaler.rds", package = "brmspack")
  if (is.null(model_file)) # Make debugging a bit easier
    model_file = "inst/extdata/inhaler.rds"
  inhaler_model = readRDS(model_file)

  # for debugging
  #  mod = brmspack:::stanmodels[["inhaler"]] 
  # required patch levels date of brms >= 2018-01-22
  stopifnot(!is.null(getCall(inhaler_model))) 
  inhaler_model$fit@stanmodel = mod 
  fit = update(inhaler_model, iter = 500, chains = 2,
               newdata = newdata, recompile = FALSE)

  #plot(fit, pars = "treat", ask = FALSE)
  fit
}
